### ISSUE TITLE
Restore incremental backups?

### ISSUE THREAD

**Issue by abhayachauhan** [mapbox/dynamodb-replicator#67]
Love the incremental backups to S3 that works really well. 

What do you use for restoring these incremental backups? 

i.e - Latest copy from S3 restored to DynamoDb, 
or 
Restoring a point in time from S3 to DynamoDb.

**Comment by abhayachauhan** [comment]
I've decided to build a tool which allows us to restore S3 incremental backups to any point in time.

https://github.com/PageUpPeopleOrg/dynamo-incremental-restore

**Comment by rclark** [comment]
:+1: Thanks for the link. We've performed one-off restores on individual records using the CLI tools in this repo, larger restores using customized scripts with help from https://github.com/mapbox/dynamodb-migrator, and full-table restores from snapshots generated by this repo's snapshot tools.

**Comment by segersniels** [comment]
@rclark Mind sharing the scripts you used to restore using dynamodb-migrator? Sorry for bringing back such an old post, but the use case looks interesting.
